BoxLayout:
    orientation: "vertical"
    Label:
        text: "Not set"
        id: main_label
    Button:
        text: "one"
        on_press: app.handle_button_press(self)
    Button:
        text: "two"
        on_press: app.handle_button_press(self)
#    BoxLayout:
#        orientation: "horizontal"
#        Button:
#            text: "three-A"
#            size_hint_x: 0.7
#        Button:
#            text: "three-B"
#            size_hint_x: 0.3